export const SIGN_IN_BEGIN = 'SIGN_IN_BEGIN';
export const SIGN_IN_SUCCESS   = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILURE = 'SIGN_IN_FAILURE';

export const SIGN_OUT_BEGIN = 'SIGN_OUT_BEGIN';
export const SIGN_OUT_SUCCESS   = 'SIGN_OUT_SUCCESS';
export const SIGN_OUT_FAILURE = 'SIGN_OUT_FAILURE';

export const VERIFY_USER_BEGIN = 'VERIFY_USER_BEGIN';
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS';